# Generated by Django 3.1.7 on 2021-03-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='cls',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='school',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
